### ISSUE TITLE
Code Coverage for just unit tests?

### ISSUE THREAD

**Issue by joshrlesch** [paveldudka/JacocoEverywhere#11]
Not really an issue, but is it possible to create a task that only runs the mock unit tests, and generates code coverage reports from that?

My current unit test tasks are `testMockDebugUnitTest`. Would like to get coverage on those tests. Is it possible with our plugin?

**Comment by paveldudka** [comment]
In its current form, JacocoEverywhere doesn't support that, but you can get what you want by forcing Gradle to exclude integration task from the execution graph:

`./gradlew createMockDebugAndroidTestCoverageReport -x :app:connectedMockDebugAndroidTest`

This way you ask Gradle to generate test report for both unit & integration tests (so JacocoEverywhere builds all the dependencies), but also with `-x` option you tell Gradle to exclude actual Integration test task. So what's gonna happen - is just a unit test portion will be executed. Kinda hacky, but should work

**Comment by joshrlesch** [comment]
This works thank you!
