### ISSUE TITLE
Exclusion strategy

### ISSUE THREAD

**Issue by LuigiPapino** [paveldudka/JacocoEverywhere#15]
I'm using with success jacoco-everywhere in my project, and it is very useful.

How can I exclude some classes or packages? Are there some examples?

**Comment by paveldudka** [comment]
Jacoco report generation is part of Android plugin and is not really under control of jacoco-everywhere. You can try one of solutions from here http://stackoverflow.com/questions/29887805/filter-jacoco-coverage-reports-with-gradle

Let me know how did it work out

**Comment by luisribeiro** [comment]
Hi there!
   Did it work to you? I tried to exclude some packages, but unsuccessfully =/

   I've tried some ways, but no one worked.

   Thank you!!

**Comment by paveldudka** [comment]
Merging this one into #18
