### ISSUE TITLE
Gradle jacoco coverage report with more than one submodule(s)?

### ISSUE THREAD

**Issue by k3b** [paveldudka/JacocoEverywhere#16]
Currently JacocoEverywhere merges jacoco reports from different tests in the same submodule. i.e.
- myProject/src/main
- myProject/src/test
- myProject/src/androidtest

Is it possible to have the report over the tests of different sub-moduls as described in 

http://stackoverflow.com/questions/38675853/gradle-jacoco-coverage-report-with-more-than-one-submodules
- myProject1/src/main
- myProject1/src/test
- myProject2/src/main
- myProject2/src/test

I alredy tried as decribed in https://discuss.gradle.org/t/merge-jacoco-coverage-reports-for-multiproject-setups/12100/6

```
task jacocoMerge(type: JacocoMerge) {
   subprojects.each { subproject ->
      executionData subproject.tasks.withType(Test)
   } 
}
```

but got the error message (using gradle-2.14)

```
* What went wrong:
Some problems were found with the configuration of task ':jacocoMerge'.
> No value has been specified for property 'jacocoClasspath'.
> No value has been specified for property 'executionData'.
> No value has been specified for property 'destinationFile'.
```

**Comment by paveldudka** [comment]
Seems like you found your answer already according to http://stackoverflow.com/questions/38675853/gradle-jacoco-coverage-report-with-more-than-one-submodules
