### ISSUE TITLE
Error : Could not get unknown property 'BINTRAY_USER' 

### ISSUE THREAD

**Issue by LuongChu12** [paveldudka/JacocoEverywhere#19]
Dear Paveldudka and everyone
I have downloaded your project and imported to build .jar file for using as plug in, however I faced problem while doing grade build
Gradler 'JacocoEverywhere-master' project refresh failed
Error : Could not get unknown property 'BINTRAY_USER' for object of type com.novoda.gradle.release.PublishExtension
Do I need to create repository in bintray.com ?
Do you have any suggestions for resolving it ?
Thank you very much

**Comment by LuongChu12** [comment]
Resolved

**Comment by sammyplexus** [comment]
@LuongChu12 , How did you resolve this issue please? I am having the same issue

**Comment by paveldudka** [comment]
Hey @sammyplexus
Sorry about this - this info is needed only when you publish to Bintray, but current config requires that even if you just want to build it.

The quickest workaround to unblock you would be to add following in your 'gradle.properties' file:

'''
BINTRAY_USER=
'''

**Comment by paveldudka** [comment]
You might also need BINTRAY_KEY specified as well.

gradle.properties:

BINTRAY_USER=
BINTRAY_KEY=

Let me know if you have further problems
